---
abstract: 'open anything'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  File::Slurp: 0
  File::Temp: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4202, CPAN::Meta::Converter version 2.132830'
keywords:
  - io
  - portable
  - slurp
  - spew
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Any
provides:
  IO::Any:
    file: lib/IO/Any.pm
    version: 0.09
requires:
  Carp: 0
  Fcntl: 0
  File::Spec: 0
  IO::AtomicFile: 0
  IO::File: 0
  IO::String: 0
  List::MoreUtils: 0
  Scalar::Util: 0
resources:
  bugtracker: http://github.com/jozef/IO-Any/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/IO-Any.git
version: 0.09
